version: '3.8'

services:
  postgres:
    image: postgres:bookworm
    container_name: gallery-app-postgres
    ports:
      - '5432:${POSTGRES_PORT}'
    env_file:
      - .env
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
volumes:
    postgres:
      driver: local
